# this is not a package, but we reuse the schema for simplicity
[package]
name = "package-api-guidelines"
version = "0.1.0"
license = "CC-BY-SA-4.0"
authors = [
  "tinger <tinger@tinger.dev>",
]
description = "A comprehensive guide on designing, maintaining and documenting package APIs."
repository = "https://github.com/typst-community/package-api-guidelines"
